fiscallizeon/clients/urls.py
from django.urls import path

from fiscallizeon.clients.admin import admin_hijack_client
from fiscallizeon.clients.views import members
from fiscallizeon.clients.views import clients
from fiscallizeon.clients.api.membros import (
    UserCoordinationMemberDisableAPIView,
    UserCoordinationMemberActiveAPIView,
)

app_name = 'clients'

urlpatterns = [
    path('', members.members_list, name='members_list'),
	path('cadastrar/', members.members_create, name='members_create'),
    path('<uuid:pk>/editar/', members.members_update, name='members_update'),
	path('<uuid:pk>/remover/', members.members_delete, name='members_delete'),
	path('<uuid:pk>/reset/', members.members_password_reset, name='members_password_reset'),
	path('configuracao/', clients.ConfigurationRedirectView.as_view(), name='configurations'),
	path('obrigatoriedade/professor/', members.obligation_teacher_configuration, name='obligation_teacher_configuration'),
	path('questoes/configuracoes/', members.QuestionsConfigurationsTemplateView.as_view(), name='questions_configurations'),
	path('configuracao/malotes/<uuid:pk>/', members.ConfigOMRConfigurationUpdateView.as_view(), name='update_client_omr_configuration'),
	path('exportar/', members.members_export, name='export_members_csv'),
 
	# Notificações
    path('configuracao/notificacoes/', members.ConfigNotificationsCreateView.as_view(), name='config_notifications_create'),
    path('configuracao/notificacoes/<uuid:pk>/', members.ConfigNotificationsUpdateView.as_view(), name='config_notifications_update'),

	# Tags de questões
	path('configuracao/tags/', members.QuestionTagListView.as_view(), name='question_tag_list'),
	path('configuracao/tags/criar', members.QuestionTagCreateView.as_view(), name='question_tag_create'),
    path('configuracao/tags/<uuid:pk>/editar/', members.QuestionTagUpdateView.as_view(), name='question_tag_update'),
    path('configuracao/tags/<uuid:pk>/remover/', members.QuestionTagDeleteView.as_view(), name='question_tag_delete'),
    
	# Padrão de impressão
	path('padrao/configuracao/', clients.ExamPrintConfigsListTemplateView.as_view(), name='print-configs-list'),
	path('padrao/configuracao/cadastrar/', clients.ExamPrintConfigsCreateTemplateView.as_view(), name='print-configs-create'),
	path('padrao/configuracao/atualizar/<uuid:pk>/', clients.ExamPrintConfigsUpdateTemplateView.as_view(), name='print-configs-update'),

	# Parceiros
	path('parceiros', clients.PartnersListView.as_view(), name='partners_list'),
	path('parceiros/cadastrar', clients.PartnerCreateView.as_view(), name='partners_create'),
	path('parceiros/editar/<uuid:pk>/', clients.PartnerUpdateView.as_view(), name='partner_update'),
	path('parceiros/deletar/<uuid:pk>/', clients.PartnerDeleteView.as_view(), name='partner_delete'),

	# Etapa de ensino
	path('etapa/ensino/configuracao/', clients.TeachingStageListTemplateView.as_view(), name='teaching-stage-list'),
	path('etapa/ensino/configuracao/cadastrar/', clients.TeachingStageCreateTemplateView.as_view(), name='teaching-stage-create'),
	path('etapa/ensino/configuracao/atualizar/<uuid:pk>/', clients.TeachingStageUpdateTemplateView.as_view(), name='teaching-stage-update'),

	# Sistema de ensino
	path('sistema/ensino/configuracao/', clients.EducationSystemListTemplateView.as_view(), name='education-system-list'),
	path('sistema/ensino/configuracao/cadastrar/', clients.EducationSystemCreateTemplateView.as_view(), name='education-system-create'),
	path('sistema/ensino/configuracao/atualizar/<uuid:pk>/', clients.EducationSystemUpdateTemplateView.as_view(), name='education-system-update'),

	path("hijack/acquire/<uuid:pk>/", admin_hijack_client, name="admin-hijack-client"),
    
	# API
    path("desativar/<uuid:pk>/", UserCoordinationMemberDisableAPIView.as_view(), name='disable-coordination-member'),
    path("ativar/<uuid:pk>/", UserCoordinationMemberActiveAPIView.as_view(), name='active-coordination-member'),
]

fiscallizeon/core/urls.py
from django.urls import path

from fiscallizeon.core import views
from fiscallizeon.core.api import celery_task_status
from fiscallizeon.mentorize.views import (
	DashboardStudentExamPreviewDetailsView,
	DashboardStudentView,
	DashboardStudentFirstAccessView
)

app_name = 'core'

urlpatterns = [
	path('tmp-page/<uuid:inspector_id>/', views.TmpAnswerPage.as_view(), name='tmp-page'),
	path('dashboard/', views.redirect_dashboard, name='redirect_dashboard'),
	path('coordenacao/', views.dashboard_coordination, name='dashboard_coordination'),
	path('fiscal/', views.dashboard_inspector, name='dashboard_inspector'),
	path('aluno/', views.dashboard_student, name='dashboard_student'),
	path('aluno/mentorize/first', DashboardStudentFirstAccessView.as_view(), name='dashboard_student_first_mentorize'),
	path('parceiro/', views.dashboard_partner, name='dashboard_partner'),
	path('', views.DashboardFreemiumView.as_view(), name='dashboard_freemium'),

	path('professor/', views.dashboard_teacher, name='dashboard_teacher'),
	path('professor/dashboard/', views.DashboardGenericTeacherView.as_view(), name='dashboard_generic_teacher'),

	path('webhook/new-student', views.webhook_new_student, name='webhook_new_student'),

	path('upload-image-paste/', views.upload_image_paste, name='upload_image_paste'),
    path('upload-image-ia/', views.upload_image_to_generate_question_with_AI, name='upload_image_ia'),


	path('upload-image/', views.upload_image, name='upload_image'),
	path('image-proxy/', views.image_proxy, name='image-proxy'),
	#APIget_generic_task_status
	path('api/task-status/', celery_task_status.get_generic_task_status, name='get_generic_task_status'),

	path('aluno/mentorize/', DashboardStudentView.as_view(), name='dashboard_student_mentorize'),
	path('aluno/mentorize/revisar/conteudo/<uuid:pk>', DashboardStudentExamPreviewDetailsView.as_view(), name='dashboard_student_mentorize_exam_review'),
	path('find-themes/', views.FindThemes.as_view(), name='find-themes'),

	path('responsaveis/', views.dashboard_parent, name='dashboard_parent'),
    
	path('hijack/login/user/', views.CustomAcquireUserView.as_view(), name='hijack-login-user'),
    path('switch-profile/', views.SwitchUserProfileView.as_view(), name='switch_user_profile'),

]

fiscallizeon/urls.py
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from drf_spectacular.views import (
    SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView,
)

from django.contrib import admin
from django.conf import settings
from django.http import HttpResponse
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from fiscallizeon.core.views import status, terms
from fiscallizeon.answers.views import AttachmentTemplateView, FileAnswerTemplateView

from fiscallizeon.applications.views import external_result_application
from fiscallizeon.accounts.views import login_view, custom_social_auth_complete
from django.views.static import serve

from fiscallizeon.candidates.views import subscribe_class
from fiscallizeon.core import http_error_handler
from fiscallizeon.core.views import analytics_coordination, analytics_detail_coordination
from fiscallizeon.ai.views import TextualDemoView

from social_core.utils import setting_name


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

handler400 = http_error_handler.bad_request
handler403 = http_error_handler.permission_denied
handler404 = http_error_handler.page_not_found
handler500 = http_error_handler.server_error

def service_worker_onesignal(request):
    response = HttpResponse(open(settings.ONESIGNAL_SERVICE_WORKER_PATH).read(), content_type='application/javascript')
    return response

urlpatterns = [

    # path('', include('pwa.urls')),
    path('',  login_view, name='login'),
    path(settings.ADMIN_URL, admin.site.urls),
    path('conta/', include('fiscallizeon.accounts.urls', namespace='accounts')),
    path('diagramacoes/', include('fiscallizeon.diagramations.urls', namespace='diagramations')),
    path('painel/', include('fiscallizeon.core.urls', namespace='core')),
    path('turmas/', include('fiscallizeon.classes.urls', namespace='classes')),
    path('aplicacoes/', include('fiscallizeon.applications.urls', namespace='applications')),
    path('fiscais/', include('fiscallizeon.inspectors.urls', namespace='inspectors')),
    path('alunos/', include('fiscallizeon.students.urls', namespace='students')),
    path('eventos/', include('fiscallizeon.events.urls', namespace='events')),
    path('provas/', include('fiscallizeon.exams.urls', namespace='exams')),
    path('candidatos/', include('fiscallizeon.candidates.urls', namespace='candidates')),
    path('disciplinas/', include('fiscallizeon.subjects.urls', namespace='subjects')),
    path('bncc/', include('fiscallizeon.bncc.urls', namespace='bncc')),
    path('membros/', include('fiscallizeon.clients.urls', namespace='clients')),
    path('gabaritos/', include('fiscallizeon.omr.urls', namespace='omr')),
    path('gabaritos/nps/', include('fiscallizeon.omrnps.urls', namespace='omrnps')),
    path('exportacao/', include('fiscallizeon.exports.urls', namespace='exports')),
    path('ensalamento/', include('fiscallizeon.distribution.urls', namespace='distribution')),
    path('materiais/', include('fiscallizeon.materials.urls', namespace='materials')),
    path('integracoes/', include('fiscallizeon.integrations.urls', namespace='integrations')),
    path('correcoes/', include('fiscallizeon.corrections.urls', namespace='corrections')),
    path('painel/analitico/', include('fiscallizeon.analytics.urls', namespace='analytics')),
    path('questoes/', include('fiscallizeon.questions.urls', namespace='questions')),
    path('respostas/', include('fiscallizeon.answers.urls', namespace='answers')),
    path('responsaveis/', include('fiscallizeon.parents.urls', namespace='parents')),
    path('notificacoes/', include('fiscallizeon.notifications.urls', namespace='notifications')),
    path('ajuda/', include('fiscallizeon.help.urls', namespace='help')),
    path('onboarding/', include('fiscallizeon.onboarding.urls')),
    path('dashboards/', include('fiscallizeon.dashboards.urls', namespace='dashboards')),
    path('tinymce/', include('tinymce.urls')),
    path('status/', status, name="status"),
    path('demo-textual/', TextualDemoView.as_view(), name="textual-demo"),

	path('termos/<str:slug>/', terms, name='terms'),
	path('inscricao/<str:slug>/', subscribe_class, name='subscribe-class'),

    
    path('anexar/<uuid:exam_teacher_subject>/<uuid:application_student>/', AttachmentTemplateView.as_view(), name='qrcode-response-attachment'), 
    path('anexar/<uuid:question_id>/<uuid:application_student_pk>/<int:number>/', FileAnswerTemplateView.as_view(), name='qrcode-response'), 
    path('resultado-avaliacao/<uuid:pk>', external_result_application, name='external_result_application'),	

    path('analytics/', analytics_coordination, name='analytics-coordination'),
    path('analytics/detail/', analytics_detail_coordination, name='analytics-detail-coordination'),

    path('api/v1/', include('fiscallizeon.api.urls', namespace='api')),
    path('api/v2/', include('fiscallizeon.api2.urls', namespace='api2')),
    
    path('OneSignalSDKWorker.js', service_worker_onesignal),

    path(f'social-auth/complete/<str:backend>{extra}', custom_social_auth_complete, name='social-auth-complete'),

    path('social-auth/', include('social_django.urls', namespace='social-auth')),
    path('api/v3/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v3/oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('api/v3/auth/', include('drf_social_oauth2.urls', namespace='drf')),
    path('api/v3/', include('fiscallizeon.app.urls', namespace='app')),
    path('hijack/', include('hijack.urls')),
    path('sitemap.xml', serve, {'document_root': settings.STATICFILES_DIRS[0], 'path': 'app_lize_map.xml'}),
]

urlpatterns.extend([
    path('docs/download/', SpectacularAPIView.as_view(), name='schema'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'),name='redoc'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
])

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

    schema_view = get_schema_view(
    openapi.Info(
        title="Fiscallize API",
        default_version='v2',
        description="Test description",
        contact=openapi.Contact(email="contato@fiscallize.com.br"),
        ),
        public=True,
    )

    urlpatterns.extend([
        re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
        path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
        path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ])

fiscallizeon/core/models.py
import uuid

from django.db import models
from django_lifecycle import LifecycleModelMixin
from tinymce.models import HTMLField


class BaseModel(LifecycleModelMixin, models.Model):
	id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
	created_at  = models.DateTimeField(verbose_name='Registrado em', auto_now_add=True, db_index=True)
	updated_at = models.DateTimeField(verbose_name='Atualizado em', auto_now=True)

	class Meta:
		abstract = True

class Config(BaseModel):
	privacy = HTMLField('Política de Privacidade')
	terms_of_use = HTMLField('Termos de uso')
	terms_of_use_inspectors = HTMLField('Termos de uso para fiscais')

fiscallizeon/core/templates/includes/card_subject_filter_student.html
<div class="col-12 col-sm-6 col-md-4 col-lg-3">
    <div class="card card-event mb-2">
        <div class="card-body pb-1 tx-13">
            {% if application_student.application.get_category_display == 'Online' %}
                <span class="badge badge-primary">Prova</span>
            {% elif application_student.application.get_category_display == 'Lista de Exercício' %}
                <span class="badge badge-success">Lista de Exercício</span>
            {% endif %}
            <h5 class="mb-0">
                {{application.exam.name}}
            </h5>
            <p class="float-right">
                {% if application.can_be_done_pc %}
                <i class="fas fa-desktop"></i>
                {% endif %}
                {% if application.can_be_done_cell %}
                <i class="fas fa-mobile-alt"></i>
                {% endif %}
                {% if application.can_be_done_tablet %}
                <i class="fas fa-tablet-alt"></i>
                {% endif %}

            </p>

            {% if application_student.application.get_category_display == 'Online' %}
                <p class="mg-b-0">{{application.date}}</p>
                <span class="tx-12 tx-color-03">de {{application.start}} até às {{application.end}}</span>
            {% elif application_student.application.get_category_display == 'Lista de Exercício' %}
                <p class="mg-b-0"><span class="font-weight-bold"> Encerra:</span> {{application.date_end|date:'d/m/Y'}} às {{application.end}}</p>
                <h6 class="mb-0 mt-2">Progresso:</h6>
                <div class="progress mb-3">
                    <div class="progress-bar text-dark" role="progressbar" aria-valuenow="0" aria-valuemin="0"
                        style="width: {{application_student.get_progress}}%;" :aria-valuenow="{{application_student.get_progress}}"
                        aria-valuemax="100">
                        {{application_student.get_progress}}%
                    </div>
                </div>              
            {% endif %}

        </div>
        <div class="card-footer tx-13">
            {% if application_student.application.get_category_display == 'Online' and not application_student.end_time and not application_student.is_blocked_by_tolerance and not application_student.application.is_time_finished %}
                <a id="buttom-{{application.pk}}"
                    href="{% url 'applications:applications_orientations_student' pk=application_student.pk %}"
                    class="btn btn-primary btn-block font-weight-bold d-none">
                    <i class="fas fa-pencil-alt"></i> Começar prova
                </a>
            {% endif %}
            {% if application_student.application.get_category_display == 'Lista de Exercício' and not application_student.application.is_time_finished %}
                <a id="buttom-{{application.pk}}" href="{% url 'applications:applications_homework_student' pk=application_student.pk %}" class="btn btn-success btn-block font-weight-bold d-none">
                    <i class="fas fa-pencil-alt"></i> Começar Atividade
                </a>
            {% endif %}
            
                {% if application_student.application.get_category_display == 'Online' %}
                    
                    {% if application_student.end_time %}
                        <button type="button" disabled="disabled" class="btn btn-danger disabled btn-block font-weight-bold">
                            Aplicação já realizada
                        </button>
                    {% elif application_student.application.is_time_finished %}
                        <button type="button" disabled="disabled" class="btn btn-danger disabled btn-block font-weight-bold">
                            Horário de prova encerrado!
                        </button>
                    {% elif application_student.is_blocked_by_tolerance %}
                        <button type="button" disabled="disabled" class="btn btn-danger disabled btn-block font-weight-bold">
                            Tempo de tolerância esgotado!
                        </button>
                    {% else %}
                        <span id="span-count-down-{{application.pk}}" class="d-none">
                            <span class="text-muted">Liberação em:</span>
                            <h5 id="count-down-{{application.pk}}" class="font-weight-bold">
                                -
                            </h5>
                        </span>
                    {% endif %}

                {% elif application_student.application.get_category_display == 'Lista de Exercício' %}
                        
                    {% if application_student.application.is_time_finished %}
                        <button type="button" disabled="disabled" class="btn btn-danger disabled btn-block font-weight-bold">
                            Horário de prova encerrado!
                        </button>
                    {% endif %}

            {% endif %}
        </div>
    </div>
</div>

<script>
    function countDown() {
        var time = ""

        $("#span-count-down-{{application.pk}}").toggleClass("d-none");

        // var countDownDate = moment("{{application.date_time_start_tz|date:'Y-m-d H:i:s'}}", 'YYYY-MM-DD HH:mm:ss')
        //     .toDate().getTime()

        var countDownDate = moment("{{application_student.date_time_start_tz|date:'Y-m-d H:i:s'}}", 'YYYY-MM-DD HH:mm:ss')
            .toDate().getTime()

        var now_datetime = moment("{% now 'Y-m-d H:i:s' %}", 'YYYY-MM-DD HH:mm:ss')

        var x = setInterval(function () {

            var now = now_datetime.toDate().getTime()

            var distance = countDownDate - now;

            if (distance < 0) {
                clearInterval(x);
                $("#span-count-down-{{application.pk}}").toggleClass("d-none");
                $("#buttom-{{application.pk}}").toggleClass("d-none");
            } else {
                var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                var seconds = Math.floor((distance % (1000 * 60)) / 1000);

                time = ('0' + hours).slice(-2) + ":" + ('0' + minutes).slice(-2) + ":" + ('0' + seconds).slice(-
                    2);

                $("#count-down-{{application.pk}}").html(time)

                now_datetime = now_datetime.add(1, 'seconds')
            }

        }, 1000);
    }

    countDown();
</script>

fiscallizeon/core/templates/includes/chatwoot.html
<script>
    (function(d,t) {
        var BASE_URL="https://chat.lizeedu.com.br";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        g.defer = true;
        g.async = true;
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: '2TZfdmT97yQ1YxKrgD2jPCNe',
            baseUrl: BASE_URL
          })
        }
    })(document,"script");

    window.addEventListener("chatwoot:ready", function () {

        {% if user and not user.is_anonymous %}
            window.$chatwoot.setUser("{{user.pk}}", {
                email: "{{user.email}}",
                name: "{{user.get_user_full_name}}",
            });
        
            window.$chatwoot.setCustomAttributes({
                nome_do_cliente: "{{user.get_clients.0.name}}",
            });
        {% endif %}
        
        {% if not user or user.is_anonymous %}
            window.$chatwoot.reset(); 
            setTimeout(function(){
                window.$chatwoot.setLabel("anonymous")
            }, 7000)
        {% elif user_type == 'student' and IS_MENTORIZZE %}
            window.$chatwoot.setLabel("mentorizze-student");
            window.$chatwoot.removeLabel("anonymous");
        {% else %}
            window.$chatwoot.setLabel("{{user.user_type}}");
            window.$chatwoot.removeLabel("anonymous");
        {% endif %}

        setTimeout(function(){
            window.$chatwoot.setLocale('pt_BR')
        }, 7000) 
    });
</script>

fiscallizeon/core/templates/includes/configurations_header.html
{% load permissions %}
<header>
    <nav class="ls add afa agv arx" style="display: flex; overflow-x: auto; border-width: 0px; border-style: solid; border-color: rgb(229, 231, 235); border-bottom-width: 1px; border-color: #E2E5ED; padding-top: 1rem; padding-bottom: 1rem;">
        <ul role="list" class="ls tn uj aad ard avv awb awk axk cer dcv" style="list-style: none; margin: 0px; min-width: 100%; flex: 0 0 auto; column-gap: 1.5rem; font-size: 0.875rem; line-height: 1.5rem; font-weight: 500;">
        {% if user|has_perm:'clients.change_clientteacherobligationconfiguration' %}
            <li><a href="{% url 'clients:obligation_teacher_configuration' %}" class="axz font-display" style="{% if request.resolver_match.url_name == 'obligation_teacher_configuration' %}color: #FEA464;{% else %}color: #9CA3AF;{% endif %}">Campos obrigatórios</a></li>
        {% endif %}
        {% if user|has_perm:'clients.change_confignotification' %}
            <li><a href="{% url 'clients:config_notifications_create' %}" class="font-display" style="{% if request.resolver_match.url_name == 'change_confignotification' or request.resolver_match.url_name == 'config_notifications_update' %}color: #FEA464;{% else %}color: #9CA3AF;{% endif %}">Notificações</a></li>
        {% endif %}
        {% if user|has_perm:'clients.change_clientteacherobligationconfiguration' %}
            <li><a href="{% url 'clients:update_client_omr_configuration' user.client.id %}" class="font-display" style="{% if request.resolver_match.url_name == 'update_client_omr_configuration' %}color: #FEA464;{% else %}color: #9CA3AF;{% endif %}">Malotes</a></li>
        {% endif %}
        {% if user|has_perm:'clients.change_clientquestionsconfiguration' %}
            <li><a href="{% url 'clients:questions_configurations' %}" class="font-display" style="{% if request.resolver_match.url_name == 'questions_configurations' %}color: #FEA464;{% else %}color: #9CA3AF;{% endif %}">Questões</a></li>
        {% endif %}
        {% if user.client_has_integration %}
            {% if user|has_perm:'integrations.view_integration' %}
                <li><a href="{% url 'integrations:integration_create_update' %}" class="font-display" style="{% if request.resolver_match.url_name == 'integration_create_update' %}color: #FEA464;{% else %}color: #9CA3AF;{% endif %}">Integrações</a></li>
            {% endif %}
        {% endif %}
        </ul>
    </nav>
</header>

fiscallizeon/core/templates/includes/confirm_modal.html
<div aria-hidden="true" class="modal  fade" id="confirmCancelModal" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirme sua ação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="max-height: fit-content; height: fit-content;">
                <h6>Você tem certeza que deseja realizar esta operação? 
                    <span class="text-muted">
                        Após confirmação não será possível desfazê-la. 
                    </span>
                </h6>
            </div>
            <div class="modal-footer">
                <form id="id_confirm_cancel_form" action="" method="POST">
                    {% csrf_token %}
                    <div class="form-buttons-w text-right">
                        <button class="btn btn-danger" type="submit">
                            <i class="os-icon os-icon-check"></i>
                            <span>Sim, confirmar</span>
                        </button>
                        <button class="btn btn-secondary" data-dismiss="modal" type="button">
                            <i class="os-icon os-icon-cancel-circle"></i>
                            <span>Não</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

fiscallizeon/core/templates/includes/footer.html
{% comment %} <footer class="footer">
  <div>
    <span>&copy; {% now "Y" %} Fiscallize v1.0.0.</span>
    <!-- <span>Criado pela <a href="#"></a></span> -->
  </div>
</footer> {% endcomment %}

fiscallizeon/core/templates/includes/messages.html
{% if messages %}
  {% with messages|slice:":1" as first_message %}
    {% for message in first_message %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3 mb-0" role="alert">
        {% if message.tags == 'success' %}
          <i data-feather="check-circle" class="mg-r-10" style="display: inline;"></i>
        {% elif message.tags == 'info' %}
          <i data-feather="alert-circle" class="mg-r-10" style="display: inline;"></i>
        {% elif message.tags == 'danger' %}
          <i data-feather="alert-octagon" class="mg-r-10" style="display: inline;"></i>
        {% elif message.tags == 'warning' %}
          <i data-feather="alert-triangle" class="mg-r-10" style="display: inline;"></i>
        {% endif %}
        <strong>
          {% if message.tags == 'success' %}
            Sucesso -
          {% elif message.tags == 'info' %}
            Informação -
          {% elif message.tags == 'danger' %}
            Erro -
          {% elif message.tags == 'warning' %}
            Aviso -
          {% endif %}
        </strong> {{ message|safe }}
      </div>
      {% endfor %}
    {% endwith %}
{% endif %}

fiscallizeon/core/templates/includes/messages_container.html
{% if messages %}
  <div class="content pb-0">
    <div class="container pd-x-0 pd-lg-x-10 pd-xl-x-0 mb-n3">
      {% include 'includes/messages.html' with messages=messages only %}
    </div>
  </div>
{% endif %}