fiscallizeon/applications/urls.py
from django.urls import path

from fiscallizeon.applications import views
from fiscallizeon.applications.api import annotation, application, notice, application_student, exams_bag
from fiscallizeon.mentorize.views import ApplicationStudentListView

app_name = 'applications'

urlpatterns = [
	path('', views.applications_list, name='applications_list'),
	path('monitoramento/', views.applications_monitoring, name='applications_monitoring'),
	path('aluno/', views.application_student_list, name='application_student_list'),
	path('aluno/<uuid:pk>', views.application_exam_student_detail, name='application_exam_student_detail'),
	path(
		'prova/<uuid:pk>/detalhe/',
		views.application_exam_student_detail_v2,
		name='application_exam_student_detail_v2',
	),
	path(
		'prova/<uuid:pk>/detalhe/melhorias/',
		views.application_exam_student_detail_insight,
		name='application_exam_student_detail_insight',
	),
	path(
		'prova/<uuid:pk>/redacao/detalhe/',
		views.ApplicationEssayDetailView.as_view(),
		name='application_student_essay_detail',
	),
	path('previo/<uuid:pk>', views.application_previous_feedback, name='application_previous_feedback'),
	# path('aluno/<uuid:pk>', views.application_student_detail, name='application_student_detail'),
	
	path('<uuid:pk>', views.applications_detail, name='applications_detail'),
	path('cadastrar/', views.applications_create, name='applications_create'),
	path('cadastrar/multiplas', views.applications_create_multiple, name='applications_create_multiple'),
	path('<uuid:pk>/editar', views.applications_update, name='applications_update'),
	path('<uuid:pk>/remover', views.applications_delete, name='applications_delete'),
	path('<uuid:pk>/divulgar', views.applications_disclose, name='applications_disclose'),
	path('<uuid:pk>/adicionar', views.applications_add_del_student, name='applications_add_del_student'),
	path('<uuid:pk>/monitorar', views.applications_monitoring_inspector, name='applications_monitoring_inspector'),
	path('<uuid:pk>/orientacoes', views.applications_orientations_student, name='applications_orientations_student'),
	path('<uuid:pk>/realizar-avaliacao', views.applications_monitoring_student, name='applications_monitoring_student'),

	path('<uuid:pk>/realizar-atividade', views.applications_homework_student, name='applications_homework_student'),

	path('impressao/', views.print_applications_list, name='print_applications_list'),
    path('tipos-aplicacoes/', views.type_application_list, name='type_application_list'),
    path('tipos-aplicacoes/cadastrar/', views.type_application_create, name='type_application_create'),
    path('tipos-aplicacoes/editar/<uuid:pk>/', views.type_application_update, name='type_application_update'),
    path('tipos-aplicacoes/remover/<uuid:pk>/', views.type_application_delete, name='type_application_delete'),
	path('exportacao-aplicacoes-pdf/', views.applications_export_pdf, name='applications_export_pdf'),
	path('importar/alunos-em-aplicacoes/', views.application_students_import, name='application_students_import'),

	#API
	path('api/', application.application_list, name='api_applications_list'),
	path('api/<uuid:pk>/change_is_printed/', application.ApplicationChangeIsPrintedAPIView.as_view(), name='api-change-is-printed'),
	path('api/<uuid:pk>/change_book_is_printed/', application.ApplicationChangeBookIsPrintedAPIView.as_view(), name='api_change_book_is_printed'),
	path('api/<uuid:pk>/change_print_ready/', application.ApplicationChangePrintReadyAPIView.as_view(), name='api_change_print_ready'),
	path('api/<uuid:pk>/iniciar-avaliacao', application.application_start_view, name='application_start'),
	path('api/<uuid:pk>/finalizar-avaliacao', application.application_end_view, name='application_end'),
	path('api/<uuid:pk>/check-finalizar-avaliacao', application.application_check_end_view, name='application_check_end'),
	path('api/<uuid:pk>/remover-aplicacao', application.application_delete_api, name='application_delete_api'),
    path('api/<uuid:pk>/token_online', application.application_token_online, name='application_token_online'),
	path('api/<uuid:pk>/exportar-malote-provas', exams_bag.export_application_exams_bag, name='export_application_exams_bag'),
	path('api/<uuid:pk>/remover-malote', exams_bag.remove_application_exam_bag, name='remove_application_exam_bag'),
	path('api/<uuid:pk>/exportar-malote-elit', exams_bag.export_application_elit_exams_bag, name='export_application_elit_exams_bag'),

	
	path('api/<uuid:pk>/duplicar', application.application_duplicate, name='application_duplicate'),

	path('api/<uuid:pk>/justificar-atraso', application.application_student_justify_delay, name='application_student_justify_delay'),
	path('api/anotacao/criar', annotation.annotation_create_api, name="annotation_create_api"),
	path('api/anotacao-aplicacao/criar', annotation.application_annotation_create_api, name="application_annotation_create_api"),
	path('api/aviso-aplicacao/criar', notice.application_notice_create_api, name="application_notice_create_api"),
	path('api/aplicacao-aluno/<uuid:pk>', application_student.application_student_exam_api, name="application_student_exam_api"),
	path('api/upload-alunos', application.application_student_upload, name="application_student_upload"),
	path('api/quantidade-paginas/<uuid:pk>', application.application_pages_amount, name="application_pages_quantity"),
	path('api/exportar-listagem-impressao/', application.export_print_list, name="application_export_print_list"),
    path('api/excecao-horario', application_student.application_student_exception_api, name="application_student_exception_api"),

 	# API para zerar prova do aluno
	path('api/clear/applicationstudent/<uuid:pk>/', application_student.ApplicationStudentClearUpdateAPIView.as_view(), name='api_clear_and_missed_applicationstudent'),
	path('api/empty/questions/applicationstudent/<uuid:pk>/', application_student.ApplicationStudentEmptyQuestionsAPIView.as_view(), name='api-set-empty-questions-applicationstudent'),
	
	
	path('api/listar/apicacoes/alunos/', application.applications_students_coordination, name='api_applications_students_coordination'),
   
	path('api/applications/checkexam/<uuid:pk>/', application.ApplicationCheckExamView.as_view(), name='application_exam_exist'),

	path('api/application-teachersubjects/<uuid:pk>/', application.teacher_subject_list_from_application, name='teacher_subject_list_from_application'),
	path('api/application-questions-report/<uuid:pk>/', application.questions_report_from_application, name='questions_report_from_application'),
	
	# Mentorize views
	path('aluno/mentorize/', ApplicationStudentListView.as_view(), name='mentorize_application_student_list'),
	
	path('api/applicationstudent/<uuid:pk>/choose/language', application_student.ApplicationStudentChooseLanguageUpdateAPIView.as_view(), name='api-applicationstudent-choose-language'),
    
	path('clear_answers/<uuid:pk>/', views.ClearAllAnswersAndRedirectView.as_view(), name='clear_all_answers')


]

fiscallizeon/core/urls.py
from django.urls import path

from fiscallizeon.core import views
from fiscallizeon.core.api import celery_task_status
from fiscallizeon.mentorize.views import (
	DashboardStudentExamPreviewDetailsView,
	DashboardStudentView,
	DashboardStudentFirstAccessView
)

app_name = 'core'

urlpatterns = [
	path('tmp-page/<uuid:inspector_id>/', views.TmpAnswerPage.as_view(), name='tmp-page'),
	path('dashboard/', views.redirect_dashboard, name='redirect_dashboard'),
	path('coordenacao/', views.dashboard_coordination, name='dashboard_coordination'),
	path('fiscal/', views.dashboard_inspector, name='dashboard_inspector'),
	path('aluno/', views.dashboard_student, name='dashboard_student'),
	path('aluno/mentorize/first', DashboardStudentFirstAccessView.as_view(), name='dashboard_student_first_mentorize'),
	path('parceiro/', views.dashboard_partner, name='dashboard_partner'),
	path('', views.DashboardFreemiumView.as_view(), name='dashboard_freemium'),

	path('professor/', views.dashboard_teacher, name='dashboard_teacher'),
	path('professor/dashboard/', views.DashboardGenericTeacherView.as_view(), name='dashboard_generic_teacher'),

	path('webhook/new-student', views.webhook_new_student, name='webhook_new_student'),

	path('upload-image-paste/', views.upload_image_paste, name='upload_image_paste'),
    path('upload-image-ia/', views.upload_image_to_generate_question_with_AI, name='upload_image_ia'),


	path('upload-image/', views.upload_image, name='upload_image'),
	path('image-proxy/', views.image_proxy, name='image-proxy'),
	#APIget_generic_task_status
	path('api/task-status/', celery_task_status.get_generic_task_status, name='get_generic_task_status'),

	path('aluno/mentorize/', DashboardStudentView.as_view(), name='dashboard_student_mentorize'),
	path('aluno/mentorize/revisar/conteudo/<uuid:pk>', DashboardStudentExamPreviewDetailsView.as_view(), name='dashboard_student_mentorize_exam_review'),
	path('find-themes/', views.FindThemes.as_view(), name='find-themes'),

	path('responsaveis/', views.dashboard_parent, name='dashboard_parent'),
    
	path('hijack/login/user/', views.CustomAcquireUserView.as_view(), name='hijack-login-user'),
    path('switch-profile/', views.SwitchUserProfileView.as_view(), name='switch_user_profile'),

]

fiscallizeon/exports/urls.py
from django.urls import path

from fiscallizeon.exports import views
from fiscallizeon.exports import api
from fiscallizeon.exports.api.importation import ImportationErrorsAPIView
from fiscallizeon.omrnps.api.nps_application_results import NPSApplicationExportResultsTaskStatusView

app_name = 'exports'

urlpatterns = [
	path('prova/<uuid:pk>', views.exam_export, name='exam_export'),
	path('prova/<uuid:pk>/erp', views.exam_export_report, name='exam_export_report'),
	path('prova/<uuid:pk>/respostas', views.exam_export_report_answers, name='exam_export_report_answers'),
	path('prova/<uuid:pk>/acertos-erros', views.ExamExportSimpleReportView.as_view(), name='exam_export_simple_report'),
	path('prova/<uuid:pk>/competencias', views.ExamExporCorrectionsReportView.as_view(), name='exam_export_corrections'),
	path('provas/erp', views.exams_export_erp, name='exams_export_erp'),
	path('provas/respostas', views.exams_export_answers, name='exams_export_answers'),
	path('provas/acertos-erros', views.ExamsSimpleExportView.as_view(), name='exams_export_simple_report'),
	path('provas/redacao/<uuid:pk>/', views.ExamExportEssayDetailView.as_view(), name='exams_export_essay'),
	
	# NPS application
	path('gabaritos/nps/', views.NPSApplicationExport.as_view(), name='nps_applications_export'),
 
	#API
	path('api/export_exams_status/<uuid:export_id>', api.exams_export_results, name='exams_export_results'),
	path('api/list_exam_results/<uuid:exam_id>', api.list_exam_results, name='list_exam_results'),
    path('api/get/errors/<uuid:pk>/', ImportationErrorsAPIView.as_view(), name='get-importation-errors')
]

fiscallizeon/urls.py
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from drf_spectacular.views import (
    SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView,
)

from django.contrib import admin
from django.conf import settings
from django.http import HttpResponse
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from fiscallizeon.core.views import status, terms
from fiscallizeon.answers.views import AttachmentTemplateView, FileAnswerTemplateView

from fiscallizeon.applications.views import external_result_application
from fiscallizeon.accounts.views import login_view, custom_social_auth_complete
from django.views.static import serve

from fiscallizeon.candidates.views import subscribe_class
from fiscallizeon.core import http_error_handler
from fiscallizeon.core.views import analytics_coordination, analytics_detail_coordination
from fiscallizeon.ai.views import TextualDemoView

from social_core.utils import setting_name


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

handler400 = http_error_handler.bad_request
handler403 = http_error_handler.permission_denied
handler404 = http_error_handler.page_not_found
handler500 = http_error_handler.server_error

def service_worker_onesignal(request):
    response = HttpResponse(open(settings.ONESIGNAL_SERVICE_WORKER_PATH).read(), content_type='application/javascript')
    return response

urlpatterns = [

    # path('', include('pwa.urls')),
    path('',  login_view, name='login'),
    path(settings.ADMIN_URL, admin.site.urls),
    path('conta/', include('fiscallizeon.accounts.urls', namespace='accounts')),
    path('diagramacoes/', include('fiscallizeon.diagramations.urls', namespace='diagramations')),
    path('painel/', include('fiscallizeon.core.urls', namespace='core')),
    path('turmas/', include('fiscallizeon.classes.urls', namespace='classes')),
    path('aplicacoes/', include('fiscallizeon.applications.urls', namespace='applications')),
    path('fiscais/', include('fiscallizeon.inspectors.urls', namespace='inspectors')),
    path('alunos/', include('fiscallizeon.students.urls', namespace='students')),
    path('eventos/', include('fiscallizeon.events.urls', namespace='events')),
    path('provas/', include('fiscallizeon.exams.urls', namespace='exams')),
    path('candidatos/', include('fiscallizeon.candidates.urls', namespace='candidates')),
    path('disciplinas/', include('fiscallizeon.subjects.urls', namespace='subjects')),
    path('bncc/', include('fiscallizeon.bncc.urls', namespace='bncc')),
    path('membros/', include('fiscallizeon.clients.urls', namespace='clients')),
    path('gabaritos/', include('fiscallizeon.omr.urls', namespace='omr')),
    path('gabaritos/nps/', include('fiscallizeon.omrnps.urls', namespace='omrnps')),
    path('exportacao/', include('fiscallizeon.exports.urls', namespace='exports')),
    path('ensalamento/', include('fiscallizeon.distribution.urls', namespace='distribution')),
    path('materiais/', include('fiscallizeon.materials.urls', namespace='materials')),
    path('integracoes/', include('fiscallizeon.integrations.urls', namespace='integrations')),
    path('correcoes/', include('fiscallizeon.corrections.urls', namespace='corrections')),
    path('painel/analitico/', include('fiscallizeon.analytics.urls', namespace='analytics')),
    path('questoes/', include('fiscallizeon.questions.urls', namespace='questions')),
    path('respostas/', include('fiscallizeon.answers.urls', namespace='answers')),
    path('responsaveis/', include('fiscallizeon.parents.urls', namespace='parents')),
    path('notificacoes/', include('fiscallizeon.notifications.urls', namespace='notifications')),
    path('ajuda/', include('fiscallizeon.help.urls', namespace='help')),
    path('onboarding/', include('fiscallizeon.onboarding.urls')),
    path('dashboards/', include('fiscallizeon.dashboards.urls', namespace='dashboards')),
    path('tinymce/', include('tinymce.urls')),
    path('status/', status, name="status"),
    path('demo-textual/', TextualDemoView.as_view(), name="textual-demo"),

	path('termos/<str:slug>/', terms, name='terms'),
	path('inscricao/<str:slug>/', subscribe_class, name='subscribe-class'),

    
    path('anexar/<uuid:exam_teacher_subject>/<uuid:application_student>/', AttachmentTemplateView.as_view(), name='qrcode-response-attachment'), 
    path('anexar/<uuid:question_id>/<uuid:application_student_pk>/<int:number>/', FileAnswerTemplateView.as_view(), name='qrcode-response'), 
    path('resultado-avaliacao/<uuid:pk>', external_result_application, name='external_result_application'),	

    path('analytics/', analytics_coordination, name='analytics-coordination'),
    path('analytics/detail/', analytics_detail_coordination, name='analytics-detail-coordination'),

    path('api/v1/', include('fiscallizeon.api.urls', namespace='api')),
    path('api/v2/', include('fiscallizeon.api2.urls', namespace='api2')),
    
    path('OneSignalSDKWorker.js', service_worker_onesignal),

    path(f'social-auth/complete/<str:backend>{extra}', custom_social_auth_complete, name='social-auth-complete'),

    path('social-auth/', include('social_django.urls', namespace='social-auth')),
    path('api/v3/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v3/oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('api/v3/auth/', include('drf_social_oauth2.urls', namespace='drf')),
    path('api/v3/', include('fiscallizeon.app.urls', namespace='app')),
    path('hijack/', include('hijack.urls')),
    path('sitemap.xml', serve, {'document_root': settings.STATICFILES_DIRS[0], 'path': 'app_lize_map.xml'}),
]

urlpatterns.extend([
    path('docs/download/', SpectacularAPIView.as_view(), name='schema'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'),name='redoc'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
])

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

    schema_view = get_schema_view(
    openapi.Info(
        title="Fiscallize API",
        default_version='v2',
        description="Test description",
        contact=openapi.Contact(email="contato@fiscallize.com.br"),
        ),
        public=True,
    )

    urlpatterns.extend([
        re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
        path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
        path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ])

fiscallizeon/applications/templates/dashboard/applications/imports/application_students_import.html
{% extends 'redesign/base.html' %}
{% load static %}

{% block title %}
  Importar alunos em múltiplas aplicações - Lize
{% endblock title %}

{% block css-additional %}
  <link rel="stylesheet" href="{% static 'administration/lib/datatables.net-responsive-dt/css/responsive.dataTables.min.css' %}">
{% endblock %}

{% block breadcrumb-fixed %}
<div class="ard cer dcv mt-3">
  <div>
    <div>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-style1 mg-b-10">
          <li class="breadcrumb-item"><a href="{% url 'applications:applications_list' %}">Aplicações</a></li>
          <li class="breadcrumb-item tw-text-orange-500" aria-current="page">Importar alunos</li>
        </ol>
      </nav>
      <div class="tw-mt-10">
        <div class="tw-mb-8">
          <h4>Importação de alunos em múltiplas aplicações (CSV)</h4>
          <span class="tw-text-gray-500 tw-text-xs">Os alunos (ou turmas) serão importados para a última aplicação cadastrada do caderno especificado na primeira coluna do arquivo.</span>
        </div>
        <div class="lize-card tw-w-fit tw-p-4 tw-mt-3 hover:tw-ring-orange-300 hover:tw-ring-2 tw-ring-opacity-50 tw-transition-all">
          <a href="{% static 'modelo_importacao_multipla.csv' %}" download>
            <div class="media">
              <span class="tx-color-04"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-download wd-60 ht-60"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg></span>
              <div class="media-body mg-l-20">
                <h6 class="mg-b-10">Modelo de importação de alunos (CSV)</h6>
                <p class="tw-text-orange-500">Você pode baixar o modelo de arquivo clicando nesse card</p>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock breadcrumb-fixed %}

{% block content-fixed %}
<div class="ard cer dcv tw-mb-16">
  <div class="" style="margin-top: 1.25rem; margin-bottom: 1rem;">
      {% if user.last_import_application_students %}
        <template>
          <div class="my-4 p-2 rounded-lg border border-info">
            <div class="row m-0">
              <div class="col d-flex align-items-center">
                <div class="mt-2">
                  <h5 class="text-info">Última importação</h5>
                  <p>Detalhes: ${lastTask.details != '' ? lastTask.details : ''}</p>
                </div>
              </div>
              <div class="col-6 col-lg-3 d-flex align-items-center justify-content-end" v-if="importationErrors.length">
                <button class="btn btn-danger" data-toggle="modal" data-target="#modalErrors">
                  Ver erro de importação
                </button>
              </div>
            </div>
          </div>
        </template>
      {% endif %}
    <form method="POST" enctype="multipart/form-data" class=" tw-w-fit tw-flex tw-flex-col tw-space-y-3 tw-items-end">
      {% csrf_token %}
      <div>
        <div class="tw-flex tw-flex-col tw-space-y-2 lize-card tw-w-fit tw-p-4">
          <label class="" for="file">Selecione o arquivo CSV...</label>
          <input type="file" class="" name="file" id="file">
        </div>
      </div>
      <div>
        <div>
          <button class="tw-flex tw-items-center tw-gap-x-1 tw-rounded-md tw-bg-blue-600 tw-px-3 tw-py-2 tw-text-sm tw-font-semibold tw-text-white tw-shadow-sm hover:tw-bg-blue-500 focus-visible:tw-outline focus-visible:tw-outline-2 focus-visible:tw-outline-offset-2 focus-visible:tw-outline-blue-600 hover:tw-text-white tw-transition-colors" type="submit">Enviar arquivo</button>
        </div>
      </div>
    </form>
    <div class="tw-mt-5 tw-w-[340px]">
      <div class="tw-flex tw-flex-col tw-space-y-2 lize-card tw-p-4">
        <h5>Unidades disponíveis:</h5>
        <ul class="tw-list-none tw-pl-3">
          <li v-for="unit in units" :key="unit.id">
            <span>${unit.name}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock content-fixed %}

{% block extra-modal %}
  
  <div aria-hidden="true" class="modal fade" id="modalErrors" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-truncate" id="modal-exam-export-title">Erro de importação</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body h-100 p-5">
          <h5 class="text-center" v-for="error in importationErrors">
            ${error}
            <br>
            <br>
            Por favor, corrija seu arquivo e envie novamente.
          </h5>
        </div>
      </div>
    </div>
  </div>
{% endblock extra-modal %}
  

{% block js-additional %}
<script src="{% static 'administration/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js' %}"></script>
<script src="{% static 'administration/lib/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<script>
  var app = new Vue({
    delimiters: ['${', '}'],
    el: '#app',
    data: {
      file: null,
      units: [
        {% for unit in units %}
          {name: "{{unit.name}}", id: "{{unit.id}}"},
        {% endfor %}
      ],
      importationErrors: [],
      lastTask: {
        status: '',
        details: '',
      }
    },
    methods: {
      checkTaskStatus() {
        axios.get("{% url 'core:get_generic_task_status' %}?task_id=IMPORT_APPLICATION_STUDENTS_{{user.id}}").then((response) => {
          if(response.data.status == 'SUCCESS') {
            this.lastTask.details = response.data.details;
            clearInterval(this.checkTaskInterval);
            if(this.lastTask.status == 'STARTED' && !response.data.details.includes('Importação de alunos em aplicações finalizada com sucesso')) {
              if(this.importationErrors.length) {
                $('#modalErrors').modal('show')
              }
            }
          } else if(response.data.status == 'FAILURE') {
            this.lastTask.details = response.data.details;
            clearInterval(this.checkTaskInterval);
          } else if (response.data.status == 'PENDING') {
            this.lastTask.details = 'Nenhuma importação iniciada';
          } else if (response.data.status == 'STARTED') {
            this.lastTask.status = response.data.status
            this.lastTask.details = 'Importação em andamento, aguarde...';
          }
        })
      },
      getImportationErrors() {
        {% if user.last_import_application_students %}
          axios.get("{% url 'exports:get-importation-errors' user.last_import_application_students.id %}").then((response) => {
            this.importationErrors = response.data
          })
        {% endif %}
      }
    },
    mounted() {
      this.checkTaskStatus()
      setTimeout(() => {
        this.getImportationErrors()
      }, 2000)

      this.checkTaskInterval = setInterval(() => {
        this.checkTaskStatus()
        this.getImportationErrors()
      }, 10000)
    }
  })
</script>
{% endblock %}